version: "3.8"

services:
  postgres:
    container_name : postgres-dev
    image: postgres:latest
    env_file:
      - ./.env.local
    ports:
      - 5432:5432
    expose:
      - 5432

  frontend:
    container_name: frontend-dev
    build:
      context: .
      target: dev
    restart: always
    command: sh -c "npx prisma migrate deploy && npm run docker:dev"
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    env_file:
      - ./.env.local
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
